### ISSUE TITLE
Retain copyright notices from rust-libp2p

### ISSUE THREAD

**Issue by mxinden** [netwarps/libp2p-rs#22]
Hi there,

I am Max, one of the maintaners of [rust-libp2p](https://github.com/libp2p/rust-libp2p/).

Let me start off by saying that I am quite happy to see an additional implementation of the libp2p specification in the Rust language based on rust-libp2p. I think your goal of offering a simplified API to the user is worth exploring, and I am curious what you come up with.

Now to my actual concern. I appreciate that you mention in your README.md that much of libp2p-rs is borrowed from rust-libp2p. In addition to this, I would like to ask you to adhere to the requirements of the MIT license of rust-libp2p, namely **to retain the Parity Technologies copyright notices in each and every file that contains logic taken from rust-libp2p as well as in the LICENSE file itself**.

For a concrete guide on how to properly fork an MIT licensed project I can recommend @fbaierl guide [HOWTO fork a MIT licensed project](https://gist.github.com/fbaierl/1d740a7925a6e0e608824eb27a429370).

**Comment by kingwel-xie** [comment]
Sure, thanks for the reminder. Will do for any files taken from rust-libp2p. 

This repo was started a few month ago, and as mentioned in Readme, it is supposed to explore the feasibility of using async/await instead of poll method to make a solid network framework in Rust. 

Please see [here](https://github.com/libp2p/rust-libp2p/issues/1659) for the background why we started this project.

**Comment by kirushik** [comment]
@kingwel-xie oh, we totally understand your reasoning behind this fork, and are super-interested to see where it would get you!

While you're returning Parity's copyright to their right places, would you be so kind to make sure that Parity Technologies is also listed in the main `LICENSE` file of the repo? I'm afraid it wouldn't be enough legally to just retain the copyright notices in the individual files.

**Comment by kingwel-xie** [comment]
Sounds fair. Will look into the Guide to figure out how to do. 

It would take a few days to fix the copyright issue. Pretty much shorthanded, and busy with Kad-dht development. Personally I'd like to fix it in the next release when Kad is ready.

**Comment by mxinden** [comment]
Fixed with https://github.com/netwarps/libp2p-rs/pull/23. Thanks.
